#%RAML 1.0
title: PPL In-Person

/challenger:
  /{challengerId}:
    get:
      description: Get the challenger with `challengerId = {challengerId}`
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "id": "0594",
                "displayName": "Lunella",
                queuesEntered: [
                  "2498",
                  "1723",
                  "9000"
                ],
                badgesEarned: [
                  "3560",
                  "6110",
                  "5504"
                ]
              }
    post:
      description: Set a displayName for a challenger with `challengerId = {challengerId}`
      body:
        application/json:
          example: |
            {
              "displayName": "Lunella"
            }
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "id": "0594",
                "displayName": "Lunella",
                queuesEntered: [
                  "2498",
                  "1723",
                  "9000"
                ],
                badgesEarned: [
                  "3560",
                  "6110",
                  "5504"
                ]
              }
/leader:
  /{leaderId}:
    get:
      description: Get the leader with `leaderId = {leaderId}`
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "id": "0594",
                "displayName": "Lunella",
                "badgeName": "Nocturnal Badge",
                queue: [
                  {
                    "challengerId": "5603",
                    "position": 0
                  },
                  {
                    "challengerId": "1234",
                    "position": 1
                  },
                  {
                    "challengerId": "7654",
                    "position": 2
                  },
                ],
                onHold: [
                  "3210",
                  "4567",
                  "8901"
                ]
              }
    post:
      description: Set a displayName for a leader with `leaderId = {leaderId}`
      body:
        application/json:
          example: |
            {
              "displayName": "Lunella"
            }
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "leaderId": "0594",
                "displayName": "Lunella",
                "badgeName": "Nocturnal Badge",
                queue: [
                  {
                    "challengerId": "5603",
                    "position": 0
                  },
                  {
                    "challengerId": "1234",
                    "position": 1
                  },
                  {
                    "challengerId": "7654",
                    "position": 2
                  },
                ],
                onHold: [
                  "3210",
                  "4567",
                  "8901"
                ]
              }
  /enqueue:
    post:
      description: Adds a challenger to a leader's queue
      body:
        application/json:
          example: |
            {
              "leaderId": "0594",
              "challengerId": "7654"
            }
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "success": "true",
                "error": "errcode" (omitted it success == true)
              }
  /dequeue:
    post:
      description: Removes a challenger from a leader's queue
      body:
        application/json:
          example: |
            {
              "leaderId": "0594",
              "challengerId": "7654",
              "challengerWin": "false" (default false if omitted)
            }
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "success": "true",
                "error": "errcode" (omitted it success == true)
              }
  /hold:
    post:
      description: Places a challenger on hold
      body:
        application/json:
          example: |
            {
              "leaderId": "0594",
              "challengerId": "7654"
            }
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "success": "true",
                "error": "errcode" (omitted it success == true)
  /unhold:
    post:
      description: Places a challenger on hold
      body:
        application/json:
          example: |
            {
              "leaderId": "0594",
              "challengerId": "7654",
              "placeAtFront": "true"
            }
      responses:
        200:
          body:
            application/json:
              example: |
              {
                "success": "true",
                "error": "errcode" (omitted it success == true)
