name: Build the site
on:
  workflow_dispatch:
    inputs:
      location:
        description: 'Which PAX is it?'
        required: true
        type: choice
        options:
          - east
          - west
          - aus
          - online
jobs:
  npm_build:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build it
        run: npm run build
